- name: passing the var from play level
  hosts: all
  vars:
    url: ganesh.com
  tasks:
    - name: accessing the vars
      ansible.builtin.debug:
        msg: url == {{url}}

- name: passing the variable from diffent file
  hosts: all
  vars_files:
   - var.yml
  tasks:
    - name: accessing the vars
      ansible.builtin.debug:
        msg: url == {{url}}

- name: task level
  hosts: all
  tasks:
    - name: accessing the vars
      vars:
        url: task.com
      ansible.builtin.debug:
        msg: url == {{url}}

- name: inventory file
  hosts: all
  tasks:
    - name: accessing the vars
      ansible.builtin.debug:
        msg: url == {{url}}

- name: register
  hosts: all
  tasks:
    - name: register task
      ansible.builtin.shell: uptime
      register: out
    - name: print output
      ansible.builtin.debug:
        msg: "{{out.stdout}}"